name: Greetings

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        issue_message: 'Hello @${{github.actor}}, thanks for creating your first issue at LearnCPP, hope you followed the guidelines.'
        pr-message: 'Congratulations!! for making your first PR at  LearnCPP, our mentors will review it soon.'

